### ISSUE TITLE
“single positional indexer is out-of-bounds”

### ISSUE THREAD

**Issue by fuentesdt** [mist-medical/MIST#51]
Results seem to be there but getting this “single positional indexer is out-of-bounds” error?

https://github.mdanderson.org/dtfuentes/hccgwas/blob/main/tumortraining.csv

https://github.mdanderson.org/dtfuentes/hccgwas/blob/main/README#L15

$ git log
commit 47739e6b595e60183d06edeaba3560c83b8243c5 (HEAD -> main, origin/main,
origin/HEAD)
Author: David Fuentes [fuentesdt@gmail.com](mailto:fuentesdt@gmail.com)
Date:   Fri Oct 18 17:58:05 2024 -0500

    ENH: pdb

commit 39fc20a71aa5ea511ae68da445de7d794467493e
Merge: 3fdfcfa 172075f
Author: David Fuentes [fuentesdt@gmail.com](mailto:fuentesdt@gmail.com)
Date:   Wed Oct 16 17:07:49 2024 -0500

    Merge pull request #5 from mist-medical/main

    updates

commit 172075fcb63d727eefa37dbe5b401246e41cd2a7
Merge: f1ef31b da0f83e
Author: Adrian Celaya [aec8@rice.edu](mailto:aec8@rice.edu)
Date:   Thu Oct 10 18:37:30 2024 -0500

    Merge pull request #49 from aecelaya/main

    Refactor evaluation to production-quality code. Fix bug in computing
average surface distance.

innovador$ pwd
/rsrch3/ip/dtfuentes/github/hccgwas
innovador$ head misttrainresults/results.csv
id,TUMOR_dice,TUMOR_haus95
1014120,0.0510545909108354,231.22499864850255
1033948,0.372221174119369,99.24212815130478
1137076,0.9028247507823778,115.55950847939775
1019920,0.3408212879340357,164.72401160729422
1118018,0.5599213003702536,25.632011235952593
1138727,0.5025447338794611,122.75585525749882
1000066,0.113971721374634,82.29823813423954
1122248,0.08889950701065076,107.34057946554975
1049537,0.3863996992791348,35.90264614203248
.
.
.

From: Twam,Awj K <ATwam@mdanderson.org> 
Sent: Monday, October 21, 2024 11:16 AM
To: Fuentes,David Thomas Alfonso <DTFuentes@mdanderson.org>
Subject: Re: crash 

I never got that specific index error- but whenever it crashed out without completing evaluation, it was mainly due to GPU usage. I think the error may be something in the dataset you are using. 

________________________________________
From: Fuentes,David Thomas Alfonso <[DTFuentes@mdanderson.org](mailto:DTFuentes@mdanderson.org)>
Sent: Monday, October 21, 2024 11:06 AM
To: Twam,Awj K <[ATwam@mdanderson.org](mailto:ATwam@mdanderson.org)>
Subject: crash
 
Awj, didn’t you have this problem before? Finishes all training and testing then crashes ? How did you fix ?
 
$ /opt/apps/miniforge/mistOct2024/bin/mist_train --data /rsrch3/ip/dtfuentes/github/hccgwas/misttrain/dataset.json --numpy /rsrch3/ip/dtfuentes/github/hccgwas/misttrainnumpy --results /rsrch3/ip/dtfuentes/github/hccgwas/misttrainresults --gpus 0 --amp --pocket   --epochs 200
 
.
.
.
 
 
Testing on fold 0 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53/53 • 0:03:12
Testing on fold 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52/52 • 0:02:50
Testing on fold 2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52/52 • 0:03:03
Testing on fold 3 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52/52 • 0:02:48
Testing on fold 4 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52/52 • 0:02:55
Evaluating predictions ╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   5/272 • 0:00:20
[rank0]: Traceback (most recent call last):
[rank0]:   File "/opt/apps/miniforge/mistOct2024/bin/mist_train", line 8, in <module>
[rank0]:     sys.exit(train_entry())
[rank0]:              ^^^^^^^^^^^^^
[rank0]:   File "/rsrch1/ip/dtfuentes/github/MIST/mist/scripts/train_entrypoint.py", line 28, in train_entry
[rank0]:     main(args)
[rank0]:   File "/rsrch1/ip/dtfuentes/github/MIST/mist/main.py", line 68, in main
[rank0]:     evaluate(args.data,
[rank0]:   File "/rsrch1/ip/dtfuentes/github/MIST/mist/evaluate_preds/evaluate.py", line 294, in evaluate
[rank0]:     path_to_truth = paths.loc[
[rank0]:                     ^^^^^^^^^^
[rank0]:   File "/opt/apps/miniforge/mistOct2024/lib/python3.12/site-packages/pandas/core/indexing.py", line 1191, in __getitem__
[rank0]:     return self._getitem_axis(maybe_callable, axis=axis)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/apps/miniforge/mistOct2024/lib/python3.12/site-packages/pandas/core/indexing.py", line 1752, in _getitem_axis
[rank0]:     self._validate_integer(key, axis)
[rank0]:   File "/opt/apps/miniforge/mistOct2024/lib/python3.12/site-packages/pandas/core/indexing.py", line 1685, in _validate_integer
[rank0]:     raise IndexError("single positional indexer is out-of-bounds")
[rank0]: IndexError: single positional indexer is out-of-bounds

**Comment by aecelaya** [comment]
That process happens entirely on the CPU. I did push some bug fixes for something like this, but it hasn't made it into a version yet. What happens if you run evaluation on this same dataset, but when you install from the latest repo?

**Comment by aecelaya** [comment]
I'm running this now with the latest code I just pushed. I'll post a screen shot of the results.

**Comment by aecelaya** [comment]
Looks like the latest code works with all metrics:

![image](https://github.com/user-attachments/assets/fbf539f1-1f37-4a95-ba7e-f5a41ec6cde0)

I'll release a v0.0.4b0 tonight with these updates.
